In [1]:
# Importing libraries
import pandas as pd

In [2]:
# Read csv while removing header as no header in original file
df = pd.read_csv('zuerich_csv.csv',header=None)
df.head(3)

,0,1,2,3,4,5,6
0,Unsere Gastronomiemitglieder haben mit uns ein...,NaN,NaN,NaN,NaN,NaN,NaN
1,8001,Restaurant Au Gratin,Bahnhofplatz 2\n8001 Zürich,www.augratin.ch,044 221 38 00 \ninfo@newszh.ch,Unsere glutenfreien Gerichte sind auf der Spei...,NaN
2,8001,Haus Hiltl,Sihlstrasse 28\n8001 Zürich,www.hiltl.ch,044 227 70 00\ninfo@hiltl.ch,"Hiltl, das bekannteste vegetarische Restaurant...",NaN

In [3]:
df.head(1)

,0,1,2,3,4,5,6
0,Unsere Gastronomiemitglieder haben mit uns ein...,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Drop first row as description and NaN only
df = df.drop(0)
df.head()

,0,1,2,3,4,5,6
1,8001,Restaurant Au Gratin,Bahnhofplatz 2\n8001 Zürich,www.augratin.ch,044 221 38 00 \ninfo@newszh.ch,Unsere glutenfreien Gerichte sind auf der Spei...,NaN
2,8001,Haus Hiltl,Sihlstrasse 28\n8001 Zürich,www.hiltl.ch,044 227 70 00\ninfo@hiltl.ch,"Hiltl, das bekannteste vegetarische Restaurant...",NaN
3,8001,Kunsthausrestaurant\n(Remimag AG),Heimplatz 1\n8001 Zürich,www.kunsthausrestaurant.ch,044 251 53 53\nkunsthausrestaurant@\nremimag.ch,Genauso kunterbunt wie die Kunst im nahegelege...,NaN
4,8001,Hitzberger Fastfood natürlich\nHauptbahnhof Zü...,Take Away Passage Bahnhofstrasse Zürich Shop-V...,www.hitzberger.ch,044 212 37 20 \n\n,Das Schnellverpflegungskonzept Hitzberger – Fa...,NaN
5,8005,SamSeS Vegetarisches Restaurant,Langstrasse 231\n8005 Zürich,www.samses.ch,044 440 13 13,"Bei uns geniessen Sie gefüllte Ravioli, Gnocch...",NaN

In [9]:
# Rename all columns
df.rename(columns = {0:'plz',1:'restaurant',2:'adresse',
                    3:'web',4:'kontakt',5:'beschreibung',6:'leer'},
          inplace=True)

#df.head()

In [10]:
df.head(3)

,plz,restaurant,adresse,web,kontakt,bschreibung
1,8001,Restaurant Au Gratin,Bahnhofplatz 2\n8001 Zürich,www.augratin.ch,044 221 38 00 \ninfo@newszh.ch,Unsere glutenfreien Gerichte sind auf der Spei...
2,8001,Haus Hiltl,Sihlstrasse 28\n8001 Zürich,www.hiltl.ch,044 227 70 00\ninfo@hiltl.ch,"Hiltl, das bekannteste vegetarische Restaurant..."
3,8001,Kunsthausrestaurant\n(Remimag AG),Heimplatz 1\n8001 Zürich,www.kunsthausrestaurant.ch,044 251 53 53\nkunsthausrestaurant@\nremimag.ch,Genauso kunterbunt wie die Kunst im nahegelege...

In [7]:
# Verify number of empty cells
df.count()

plz            15
restaurant     15
adresse        15
web            15
kontakt        15
bschreibung    15
leer            0
dtype: int64

In [8]:
# Drop last column ('leer') as it is empty
df.drop(['leer'], axis=1,inplace=True)
df.head()

,plz,restaurant,adresse,web,kontakt,bschreibung
1,8001,Restaurant Au Gratin,Bahnhofplatz 2\n8001 Zürich,www.augratin.ch,044 221 38 00 \ninfo@newszh.ch,Unsere glutenfreien Gerichte sind auf der Spei...
2,8001,Haus Hiltl,Sihlstrasse 28\n8001 Zürich,www.hiltl.ch,044 227 70 00\ninfo@hiltl.ch,"Hiltl, das bekannteste vegetarische Restaurant..."
3,8001,Kunsthausrestaurant\n(Remimag AG),Heimplatz 1\n8001 Zürich,www.kunsthausrestaurant.ch,044 251 53 53\nkunsthausrestaurant@\nremimag.ch,Genauso kunterbunt wie die Kunst im nahegelege...
4,8001,Hitzberger Fastfood natürlich\nHauptbahnhof Zü...,Take Away Passage Bahnhofstrasse Zürich Shop-V...,www.hitzberger.ch,044 212 37 20 \n\n,Das Schnellverpflegungskonzept Hitzberger – Fa...
5,8005,SamSeS Vegetarisches Restaurant,Langstrasse 231\n8005 Zürich,www.samses.ch,044 440 13 13,"Bei uns geniessen Sie gefüllte Ravioli, Gnocch..."

In [12]:
# Creating a copy of my df to clean up columns with Regex
mdf = df.copy()

In [13]:
# Isolate row 4 (Index 3)
mdf.iloc[[3]]

,plz,restaurant,adresse,web,kontakt,bschreibung
4,8001,Hitzberger Fastfood natürlich\nHauptbahnhof Zü...,Take Away Passage Bahnhofstrasse Zürich Shop-V...,www.hitzberger.ch,044 212 37 20 \n\n,Das Schnellverpflegungskonzept Hitzberger – Fa...

In [16]:
# Set option to display all characters within a column
pd.set_option('display.max_colwidth', None)

In [17]:
# Verify it worked
mdf[['adresse']].iloc[[3]]

                                                                  adresse
4  Take Away Passage Bahnhofstrasse Zürich Shop-Ville Zürich Hauptbahnhof